{% set name = "sedflux" %}
{% set version = "2.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/mcflugen/{{ name }}
  git_branch: add-function-pointers

requirements:
  build:
    - cmake
    - clangxx_osx-64 [osx]
    - gxx_linux-64 [linux]
    - pkg-config [osx]
    - glib
    - libiconv [osx]
  run:
    - libgcc [osx]
    - glib [osx]
    - libiconv [osx]

test:
  commands:
    - sedflux -h

build:
  number: 4

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  summary: A stratigraphic basin-filling model
  description: |
    Sedflux-2.0 is the newest version of the Sedflux basin-filling
    model. Sedflux-2.0 provides a framework within which individual
    process-response models of disparate time and space resolutions
    communicate with one another to deliver multi grain sized
    sediment load across a continental margin.
  doc_url: http://sedflux.readthedocs.io/
  dev_url: http://github.com/mcflugen/sedflux
