{% set name = "sedflux" %}
{% set version = "2.2" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: 1a734ffbf9d654035db60abd95adcefed9537048d57ee542bd97300a77b1e7f5

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - pkg-config [osx]
    - glib
    - libiconv [osx]
  run:
    - libgcc [osx]
    - glib
    - libiconv [osx]

test:
  commands:
    - sedflux -h

build:
  number: {{ build }}

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  summary: A stratigraphic basin-filling model
  description: |
    Sedflux-2.0 is the newest version of the Sedflux basin-filling
    model. Sedflux-2.0 provides a framework within which individual
    process-response models of disparate time and space resolutions
    communicate with one another to deliver multi grain sized
    sediment load across a continental margin.
  doc_url: http://sedflux.readthedocs.io/
  dev_url: http://github.com/mcflugen/sedflux
