{% set name = "sedflux" %}
{% set version = "2.2.1" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/mcflugen/{{ name }}/archive/v{{ version }}.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  sha256: 9e2ecf03ec8ef3fece0ffcb7e18892dd5dcb5b556b062967696d2d347a2eb411

requirements:
  # build:
  #   - cmake
  #   - {{ compiler('c') }}
  #   - pkg-config [osx]
  #   - glib
  #   - libiconv [osx]
  # run:
  #   - libgcc [osx]
  #   - glib
  #   - libiconv [osx]
  build:
    - cmake
    - gcc # [not win]
      # - isl 0.12.2 # [not win]
    - pkg-config [osx]
    - glib [osx]
  run:
    - libgcc
    - glib [osx]

test:
  commands:
    - sedflux -h

build:
  number: {{ build }}

about:
  home: https://github.com/mcflugen/sedflux
  license: MIT
  summary: A stratigraphic basin-filling model
  description: |
    Sedflux-2.0 is the newest version of the Sedflux basin-filling
    model. Sedflux-2.0 provides a framework within which individual
    process-response models of disparate time and space resolutions
    communicate with one another to deliver multi grain sized
    sediment load across a continental margin.
  doc_url: http://sedflux.readthedocs.io/
  dev_url: http://github.com/mcflugen/sedflux
