language: generic
os:
- linux
- osx
env:
  global:
  - THIS_PACKAGE=sedflux
  - TRAVIS_PYTHON_VERSION="2.7"
  - NUMPY_VERSION="1.9"
  - secure: rxW1rnyfUsc7jS1opjLqGNgbsxTmxdDHgTazQBt66lKdwyrFHiFQzqwK+lu2mm3TvSSZY39TEegxRuLnNS7xY448h3fhrZhAQU7tsZRRwS9bsP4qo2E3kt5U8vRVYd9rsC/0Nesu6uy9mBpo22R8REWiYcAJhEaDIi44pcEApdfiskI5rtWkUkyct5LTco1YC7ADNisVWSt7OCp29ZvYOowsmvuXif40ZzlvFo4Nqt6tnYHzmGYIJJh4PGcCI4st8S1xzw9Fpwp8aJ5SlwlkykI6oRGdFwhGMiVXxS0kJ4x9jgz2TZWflQEAl1Y+R3zR7r2fhHLm0JpwvlJ7Gwaslz1FbVzShTz/bs18L89bDL5Q2sx9q0eyW1yu2/F3vgfFmzm3NcAoOZMoncPUd6NleZmYe/kmNvQk1wxnkRxxsIGa6b5Nj6ruJ0cfCWP842buur61rwJbvvKNZfx0isEJMxY2kb9Htx67HfvgbNXd0rMrQA0gCjTxzQ7esxwP4OzwBWSwp/+5/cvpodqGWGXwyB2I0vdiByKkNewDwidpvonCV5qj8Q0hIPMNo2QXsev5dQ5gc2fBnfaVqciWXOnOgvW8uBiUvqyfzlBbVSC2kHQgmfS+WZsz+tkdlc0kIriwj2V8TuEQnqbzKrswVGYwhtRr7L7MvfO6SHC27RPFLBQ=
sudo: false
install:
- bash ci/travis/install_python.sh $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
script:
- conda build recipe -c conda-forge -c csdms/channel/dev -c csdms
after_success:
- if [[ $TRAVIS_BRANCH == "master" ]]; then export CHANNEL="main"; fi
- bash ci/travis/deploy_to_anaconda.sh $THIS_PACKAGE
