language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="http://repo.continuum.io/miniconda/Miniconda-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: NBM8JsN2he4TThQR13mvPpRTQ0dW0Q59wQitcnsIfqcFu3O3TmCiYVoptLCk/XCfYOzLspzVbhUzAJm5AnwWtywnYVaZxuyVng591RaJpPzj2Hv/r6PMW9IbDD9pQNscXor4bIAgStO7T61WdU6+6VrkF/wb1B4I1nFVmu5RbIxyah9jxYJM1XGwc95vAtVzgS3lPyMMWW+HfKhIVfnDpu8QvtVH5ey58TprQqvBLnC9LZmN5g4m/iv2M4aBFrEb2zbcycPQvdJ5opZ9azvsosnlMmkAZDfd16vdLIsffEb9OfwnIk7luxUx4eZBTaA6exC+o4xNvxhnyg4yuimJijmPDJoJKK6Uszw0M5JjT3iSK0iQ9i9HBfUzFSaxD5smEU1VksaVEknHI359nk1nsvk8OiKLgUaK67aPJhMG+7pENfFk4WIEnx/QITdYjVBbeQyvsbcrHQiEvF5jeaTfwTZPiGq9/0brF5H2QmImMw0lLhgwFp+AFiAX8dbpsixI4O39DPfXPObRqpMeAlQW+qW4kqGxioC5eBhtS/xtqOZeUatug/lLqw4ZZEy9Et6Tx4sLJqtUZbD1RiOW+Q88FpAn8DVujYhXG4M/Venra+13dLTrjStHNvNuEH5EvvgaAENZlXoQqRSrnxOl9osUyxpi9o7v6JL6QqXO8SFa3z4=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack
  --token=-
