language: generic
os:
- linux
- osx
env:
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda2-latest"
  - TRAVIS_PYTHON_VERSION="2.7"
  - secure: "au73FzdQsX6doOmsQ+bxiyCcpMIPk9eL8UgKDkQDO9L3Sqko9PVlpeI48xfjpzDhqgtIas3c4ve4dpgEJJquG8ukkYxqlK5W0iJp9rFJbt1NEMRXB+JNNkygZ39wT13MVYN3+WI7gVOzZoBskM+Ldug4xiKopwCtSRCq+P1wr0rCLYhvwB1h0lUh+TOG8aLl50q/DySP0KzoNOoxM8akz75UaGsB9OWX27J3ITUv4hgB1AfxoxHYPBE0kmsOdIWHiYIJSoH7F5X/eLDtoIYTKLCISmSs7z+l2vHV/npvAkIUKpC3XUw+igaKPfUjk7ME20ywncg/Eb4rMxpqCkkSIzTjkpm6CYwR2YMidN9fC933q2+G9A18H89SViQwiZmmUz+guv9MLbmwFLCO2hcVsoAicGqUd1eH//c95HlBQS+WPl2V95JUT5PA+UDTygfPS2eLxyuGS1at5bfOdHCu4yD7JMy3AvaRsAt3DhBqTdmsxO9CPuqCqoL0Ikm0hr1UN9wGwKFGzZb4WpxvKkI6Os8JnVtiBPGxW2Hrn2ukAebNGN6N/bMnfRyzzIge4QQUrnq/uVL2nKnk6I49idT8+IDFBjeLFwFhdbrlJQcsbbUfqtMBn3WoxgLcoW6i4/NcuOcMmtaunHbg+9EbUpGPNrQwS6Tc2iyMDHhyypKHpWY="
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda clean --all
- conda install python=$TRAVIS_PYTHON_VERSION
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c conda-forge -c defaults -c csdms-stack --old-build-string
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --old-build-string --token=-
