language: generic
os:
- linux
- osx
env:
  global:
  - THIS_PACKAGE=sedflux
  - TRAVIS_PYTHON_VERSION="2.7"
  - NUMPY_VERSION="1.9"
  - secure: kKTZd0DNlrr79F7YDSjGQ9y8HJew4zqHgZoshlKisWHT9k7qyi4AxxejN1VarN/BYFDyYYuF7elzv1VGZsYKJ0oAP1H22wWLhV87KDYgBZFBlQinKpzSq+UkHTXjvgBBu1zSzFQtI79sfSVUZfVY9Xu4jl1VcBAavz3NV34oiKYAgtBkHUeuPEwYKRNpns8LlZDEtG01+GGOvTcEGGc+4ZJiUGvy7nhyi9Wf1sNbKA0lXTUVJVKuGFOVMc+u0Ng35ZfcQNPIWl9Cm2e5u+gfRk+C3OQTOGT68H/MZGOW9s4XUI/u+KVKMoeGuoCTdZn6zrFBtpCHKzoSf/Rvn78usQeJV5J5VmHJdTCxHUxujrcjqRnReHt4t0WY+wYLP1fRUHt2phqdUCwOLIJVKHmUW4T6kLwLbgEBU5w75+STl+071NYGlmGinbPtAeTs31tE/S60If+rbzBHZHhR5A7M/j91QPTcz4u0BtpP45A39JLpCv2wD20r8k9YTQie5L7HWgFM/2yGlGDCMEd66IaLUgRh8IjqQID1BtJuGqEUpTb2fmXtNK6g/ZqC2sBLis99/i2Pc+LACg0setmz6EZoYt/eIXN/QLiflxjla/AUc/hvDexwV7aUjMsDH80iXty3V6NBDDrnwqCkTkGY9nMo3Mo65C0SWxqnX6qbA8AweNA=
sudo: false
install:
- bash ci/travis/install_python.sh $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
script:
- conda build recipe -c conda-forge -c csdms/channel/dev -c csdms
after_success:
- if [[ $TRAVIS_BRANCH == "master" ]]; then export CHANNEL="main"; fi
- bash ci/travis/deploy_to_anaconda.sh $THIS_PACKAGE
